// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'API_KEY_HERE',
    appId: '1:789221463505:web:2679f1d710691e8c623cf0',
    messagingSenderId: '789221463505',
    projectId: 'taxiapp-3a1a7',
    authDomain: 'taxiapp-3a1a7.firebaseapp.com',
    storageBucket: 'taxiapp-3a1a7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'API_KEY_HERE',
    appId: '1:349583206100:android:2250e00430f139168a7d41',
    messagingSenderId: '349583206100',
    projectId: 'taxi-4fc44',
    storageBucket: 'taxi-4fc44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'API_KEY_HERE',
    appId: '1:349583206100:ios:60533651004c693f8a7d41',
    messagingSenderId: '349583206100',
    projectId: 'taxi-4fc44',
    storageBucket: 'taxi-4fc44.appspot.com',
    iosBundleId: 'com.example.googleMap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'API_KEY_HERE',
    appId: '1:789221463505:ios:87a17b38f9d48f96623cf0',
    messagingSenderId: '789221463505',
    projectId: 'taxiapp-3a1a7',
    storageBucket: 'taxiapp-3a1a7.appspot.com',
    iosBundleId: 'com.example.googleMap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'API_KEY_HERE',
    appId: '1:349583206100:web:263292ae89ad7fa78a7d41',
    messagingSenderId: '349583206100',
    projectId: 'taxi-4fc44',
    authDomain: 'taxi-4fc44.firebaseapp.com',
    storageBucket: 'taxi-4fc44.appspot.com',
  );

}
